# Generated by Django 4.0.5 on 2022-06-26 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(blank=True, max_length=12, null=True, unique=True)),
                ('profile_img', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default=None, force_format='PNG', keep_meta=False, null=True, quality=80, size=[100, 100], upload_to='account/profile_img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
